// <auto-generated />
namespace Infrastructure.UserContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class SeedMe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedMe));
        
        string IMigrationMetadata.Id
        {
            get { return "201501262136518_SeedMe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
