// <auto-generated />
namespace AngularJSAuthentication.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update_RefreshTokens_Schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_RefreshTokens_Schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201410270946093_Update_RefreshTokens_Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
